services:
  web:
    image: busybox:latest
    container_name: fabrica-games
    ports:
      - "4321:80"
    volumes:
      - ./src:/var/www/html
    command: >
      /bin/sh -c "
      busybox httpd -f -p 80 -h /var/www/html
      "
    restart: always
    networks:
      - fabrica-network

networks:
  fabrica-network:
    external: true